openapi: 3.0.0
info:
  x-skaffolder-id-project: 604c9ed8a3e0491123242b06
  title: tasktwo
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /student:
    post:
      x-skaffolder-id: 604ca2aba3e0491123242b99
      x-skaffolder-name: create
      x-skaffolder-id-resource: 604ca169a3e0491123242b96
      x-skaffolder-resource: student
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - student
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/student"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: integer
                gpa:
                  type: number
                name:
                  type: string
                registration_date:
                  type: integer
    get:
      x-skaffolder-id: 604ca2aba3e0491123242b9f
      x-skaffolder-name: list
      x-skaffolder-id-resource: 604ca169a3e0491123242b96
      x-skaffolder-resource: student
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - student
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student"
  "/student/{id}":
    delete:
      x-skaffolder-id: 604ca2aba3e0491123242ba0
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 604ca169a3e0491123242b96
      x-skaffolder-resource: student
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - student
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 604ca2aba3e0491123242b9b
      x-skaffolder-name: get
      x-skaffolder-id-resource: 604ca169a3e0491123242b96
      x-skaffolder-resource: student
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - student
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/student"
    post:
      x-skaffolder-id: 604ca2aba3e0491123242b9a
      x-skaffolder-name: update
      x-skaffolder-id-resource: 604ca169a3e0491123242b96
      x-skaffolder-resource: student
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - student
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/student"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/student"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    student:
      x-skaffolder-id: 604ca169a3e0491123242b96
      x-skaffolder-id-db: 604c9ed8a3e0491123242b07
      x-skaffolder-id-entity: 604ca169a3e0491123242b91
      x-skaffolder-url: /student
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        date_of_birth:
          type: integer
          x-skaffolder-id-attr: 604ca169a3e0491123242b93
          x-skaffolder-type: Date
        gpa:
          type: number
          x-skaffolder-id-attr: 604ca169a3e0491123242b94
          x-skaffolder-type: Number
        name:
          type: string
          x-skaffolder-id-attr: 604ca169a3e0491123242b92
          x-skaffolder-type: String
          x-skaffolder-required: true
        registration_date:
          type: integer
          x-skaffolder-id-attr: 604ca169a3e0491123242b95
          x-skaffolder-type: Date
      x-skaffolder-relations: 
      required:
        - _id
        - name
  x-skaffolder-db:
    - x-skaffolder-id: 604c9ed8a3e0491123242b07
      x-skaffolder-name: tasktwo_db
  x-skaffolder-page:
    - x-skaffolder-id: 604c9ed9a3e0491123242b0f
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 604ca2aba3e0491123242b9e
      x-skaffolder-roles: []
    - x-skaffolder-id: 604ca2aba3e0491123242b98
      x-skaffolder-name: studentEdit
      x-skaffolder-url: /students/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 604ca169a3e0491123242b96
      x-skaffolder-services:
        - 604ca2aba3e0491123242b99
        - 604ca2aba3e0491123242b9a
        - 604ca2aba3e0491123242b9b
        - 604ca2aba3e0491123242ba0
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 604ca2aba3e0491123242b9e
      x-skaffolder-name: studentList
      x-skaffolder-url: /students
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 604ca169a3e0491123242b96
      x-skaffolder-services:
        - 604ca2aba3e0491123242ba0
        - 604ca2aba3e0491123242b9f
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 604ca2aba3e0491123242b98
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 604c9ed9a3e0491123242b12
      x-skaffolder-name: ADMIN
